# Generated by Django 4.1.5 on 2023-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='Enter seat number', max_length=20)),
                ('seat_class', models.CharField(choices=[('1', 'FIRST'), ('2', 'BUSINESS'), ('3', 'ECONOMY'), ('4', 'EMERGENCY')], default='3', max_length=10)),
                ('seat_location', models.CharField(choices=[('1', 'Window seat'), ('2', 'Middle seat'), ('3', 'Aisle seat')], default='3', max_length=20)),
                ('seat_flag', models.CharField(choices=[('1', 'TAKEN'), ('2', 'SELECTED'), ('3', 'AVAILABLE')], default='3', max_length=15)),
                ('seat_price', models.CharField(choices=[('1', '50'), ('2', '25'), ('3', '10')], default='3', max_length=15)),
            ],
            options={
                'ordering': ['-seat_number', 'seat_class', 'seat_location', 'seat_flag'],
            },
        ),
    ]
