# Generated by Django 4.1.4 on 2023-01-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='Enter seat number', max_length=20)),
                ('seat_class', models.CharField(choices=[('1', 'FIRST'), ('2', 'BUSINESS'), ('3', 'ECONOMY'), ('4', 'EMERGENCY')], default='3', max_length=10)),
                ('seat_location', models.CharField(choices=[('1', 'Window seat'), ('2', 'Middle seat'), ('3', 'Aisle seat')], default='3', max_length=20)),
                ('seat_price', models.CharField(help_text='Enter price', max_length=20)),
            ],
            options={
                'ordering': ['-seat_number', 'seat_class', 'seat_price'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(help_text='Enter your name', max_length=50)),
                ('passenger_age', models.IntegerField(help_text='Enter your age')),
                ('passenger_phone', models.IntegerField(help_text='Enter your phone number')),
                ('passenger_dob', models.DateField()),
            ],
        ),
    ]
