# Generated by Django 4.1.4 on 2023-01-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlineseat',
            options={'ordering': ['-seat_number', 'seat_class']},
        ),
        migrations.RemoveField(
            model_name='airlineseat',
            name='seat_price',
        ),
    ]
