# Generated by Django 4.1.4 on 2023-01-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_airlineseat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlineseat',
            name='seat_flag',
            field=models.CharField(choices=[('1', 'TAKEN'), ('2', 'SELECTED'), ('3', 'AVAILABLE')], default='3', max_length=15),
        ),
    ]
