# Generated by Django 4.1.4 on 2023-01-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_airlineseat_seat_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlineseat',
            options={'ordering': ['-seat_number', 'seat_class', 'seat_flag']},
        ),
    ]
