# Generated by Django 4.1.4 on 2023-01-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_airlineseat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlineseat',
            options={'ordering': ['-seat_number', 'seat_class', 'seat_location', 'seat_flag']},
        ),
    ]
