# Generated by Django 4.1.5 on 2023-01-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_airlineseat_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.AddField(
            model_name='airlineseat',
            name='seat_price',
            field=models.CharField(choices=[('1', '50'), ('2', '25'), ('3', '10')], default='3', max_length=15),
        ),
    ]
